name: Python package

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Check formatting
        run: |
          python3 -m pip install black
          black .
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r custom_components/csnet_home/requirements-dev.txt
      - name: Run pytest
        run: |
          pytest --cov=custom_components
